# Generated by Django 5.1.4 on 2025-02-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=10, unique=True, verbose_name='Contact Number')),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('fav_cuisine', models.CharField(choices=[('PU', 'PUNJABI'), ('SR', 'SOUTH INDIAN'), ('GU', 'GUJARATI'), ('RA', 'RAJASTHANI'), ('MA', 'MAHARASHTRIAN'), ('IT', 'ITALIAN'), ('CH', 'CHINESE'), ('MX', 'MEXICAN')], max_length=2, verbose_name='Cuisine Type')),
            ],
        ),
    ]
