# Generated by Django 5.1.4 on 2025-02-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PU', 'PUNJABI'), ('SR', 'SOUTH INDIAN'), ('GU', 'GUJARATI'), ('RA', 'RAJASTHANI'), ('MA', 'MAHARASHTRIAN'), ('IT', 'ITALIAN'), ('CH', 'CHINESE'), ('MX', 'MEXICAN'), ('TH', 'THAI'), ('JP', 'JAPANESE')], max_length=2, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fav_cuisine',
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_cuisines',
            field=models.ManyToManyField(blank=True, to='app.cuisine'),
        ),
    ]
