# Generated by Django 5.1.4 on 2025-02-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chef_food_item_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='event',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='items',
        ),
    ]
