# Generated by Django 5.1.4 on 2025-02-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_event_chef_remove_event_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(choices=[('8AM', '8AM'), ('9AM', '9AM'), ('10AM', '10AM'), ('11AM', '11AM'), ('12PM', '12PM'), ('1PM', '1PM'), ('2PM', '2PM'), ('3PM', '3PM'), ('4PM', '4PM'), ('5PM', '5PM'), ('6PM', '6PM'), ('7PM', '7PM'), ('8PM', '8PM'), ('9PM', '9PM'), ('10PM', '10PM'), ('11PM', '11PM')], max_length=4, unique=True),
        ),
    ]
