# Generated by Django 5.1.4 on 2025-02-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favorite_cuisines',
        ),
        migrations.CreateModel(
            name='FavCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('favorite_cuisines', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='favcuisine', to='app.cuisine')),
            ],
        ),
    ]
