# Generated by Django 5.1.4 on 2025-02-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_customer_favorite_cuisines_favcuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorite_cuisines',
            field=models.ManyToManyField(blank=True, related_name='favcuisine', to='app.cuisine'),
        ),
        migrations.AlterField(
            model_name='food_item',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cuisine', to='app.cuisine'),
        ),
        migrations.DeleteModel(
            name='FavCuisine',
        ),
    ]
