# Generated by Django 5.1.4 on 2025-02-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customer_favorite_cuisines_alter_food_item_cuisine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorite_cuisines',
            field=models.ManyToManyField(blank=True, to='app.cuisine'),
        ),
        migrations.AlterField(
            model_name='food_item',
            name='cuisine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Cuisine', to='app.cuisine'),
        ),
    ]
